### ISSUE TITLE
where to after installation

### ISSUE THREAD

**Issue by kristiankamper** [AThomsen/home-assistant_xolta_battery#2]
Hey AThomsen.

I presume you are danish hence the xolta battery is a danish product.

In danish:

Jeg har prøvet at finde hoved og hale i hvordan jeg kommer videre efter at have angivet min device_ID i template og på et kort.

Hvor angiver jeg login informationer til xolta?

**Comment by AThomsen** [comment]
Hej
Når du har installeret både integration og add-on, kan du under Settings, _Devices and services_ finde Xolta solar battery under Add integrations.
